
- hosts: web
  tasks:
  - name: "copy website"
    copy:
      src: site/
      dest: /var/www/default
  - name: "Replace line in file examples"
    replace: 
      path: /var/www/default/index.html
      regexp: '(Hello\sWorld)'
      replace: '\1 {{ hostname }}'
      backup: yes